# Generated by Django 6.0 on 2025-12-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('team', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='DAY', max_length=10)),
                ('date_for', models.DateField(help_text='Date this handover is for')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='OPEN', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_for', '-created_at'],
            },
        ),
    ]
